/* SUNDIALS configuration header file */

#define SUNDIALS_PACKAGE_VERSION "2.6.0"

#define SUNDIALS_DOUBLE_PRECISION 1

#define SUNDIALS_USE_GENERIC_MATH 0

#define SUNDIALS_BLAS_LAPACK 0

#define SUNDIALS_EXPORT